function Hd = bpf
%BPF Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.12 and Signal Processing Toolbox 9.0.
% Generated on: 15-Nov-2023 23:59:56

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in MHz.
Fs = 2.0;  % Sampling Frequency

Fstop1 = 0.495;     % First Stopband Frequency
Fpass1 = 0.496;     % First Passband Frequency
Fpass2 = 0.504;      % Second Passband Frequency
Fstop2 = 0.505;      % Second Stopband Frequency
Astop1 = 60;          % First Stopband Attenuation (dB)
Apass  = 1;           % Passband Ripple (dB)
Astop2 = 80;          % Second Stopband Attenuation (dB)
match  = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
